mlebreuil/netbox-contract

- pyproject.toml
- src/netbox_contract/__init__.py
> Update version to 1.0.4

- src/netbox_contract/api/serializers.py
- src/netbox_contract/filtersets.py
- src/netbox_contract/forms.py
- src/netbox_contract/tables.py
- src/netbox_contract/templates/netbox_contract/contract.html
> Add contract status to forms

- src/netbox_contract/tables.py
> Invoice list dos not show contract link correctly

- pyproject.toml
- src/netbox_contract/__init__.py
> Package v1.0.6

- README.md
- pyproject.toml
- src/netbox_contract/__init__.py
- src/netbox_contract/models.py
> internal partie filed

- pyproject.toml
- src/netbox_contract/__init__.py
- src/netbox_contract/filtersets.py
- src/netbox_contract/search.py
> Add seach functionality to contract and invoices

- README.md
- pyproject.toml
- src/netbox_contract/__init__.py
- src/netbox_contract/navigation.py
> top level navigation option

- README.md
- pyproject.toml
- src/netbox_contract/__init__.py
remove confusion with repo name
> update package name to netbox-contract

- src/netbox_contract/views.py
Initial invoice form data depends on linked
contract invoice frequency
> Invoice intial  amount depends on frequency

- src/netbox_contract/views.py
Period end should be calculated based on the invoice
frequency minus one day
> invoice period end is start plus freq minus 1 day

- src/netbox_contract/templates/netbox_contract/contract.html
- src/netbox_contract/templates/netbox_contract/invoice.html
> Add breadcrumbs to contracts and invoices view

- README.md
- src/netbox_contract/filtersets.py
modified:   src/netbox_contract/filtersets.py
> Update contract filterset

- README.md
- pyproject.toml
- src/netbox_contract/__init__.py
- src/netbox_contract/navigation.py
- src/netbox_contract/templates/contract_assignements_bottom.html
- src/netbox_contract/templates/contract_list_bottom.html
- src/netbox_contract/templates/netbox_contract/contract.html
modified:   pyproject.toml
modified:   src/netbox_contract/__init__.py
modified:   src/netbox_contract/navigation.py
modified:   src/netbox_contract/templates/contract_assignements_bottom.html
modified:   src/netbox_contract/templates/contract_list_bottom.html
modified:   src/netbox_contract/templates/netbox_contract/contract.html
> permission management

- assignement_import.csv
- src/netbox_contract/forms.py
- src/netbox_contract/navigation.py
- src/netbox_contract/urls.py
- src/netbox_contract/views.py
new file:   assignement_import.csv
modified:   src/netbox_contract/navigation.py
modified:   src/netbox_contract/urls.py
modified:   src/netbox_contract/views.py
> Add contract assignement import possibility

- README.md
- src/netbox_contract/api/views.py
modified:   src/netbox_contract/api/views.py
> Correct an API issue with the Invoice model

- src/netbox_contract/forms.py
> Add comment ot the contract impot form

- README.md
- src/netbox_contract/tables.py
- src/netbox_contract/views.py
modified:   src/netbox_contract/tables.py
modified:   src/netbox_contract/views.py
> Add fields to the contract assignment bottom tables

- src/netbox_contract/filtersets.py
- src/netbox_contract/forms.py
- src/netbox_contract/tables.py
modified:   src/netbox_contract/filtersets.py
modified:   src/netbox_contract/tables.py
> Fix missing import export contract and invoice fields

- README.md
- pyproject.toml
- src/netbox_contract/__init__.py
- src/netbox_contract/forms.py
modified:   pyproject.toml
modified:   src/netbox_contract/__init__.py
> Remove MultipleChoiceFields update Readme

- src/netbox_contract/api/serializers.py
- src/netbox_contract/templates/netbox_contract/contract.html
- src/netbox_contract/templates/netbox_contract/invoice.html
modified:   src/netbox_contract/api/serializers.py
modified:   src/netbox_contract/templates/netbox_contract/contract.html
modified:   src/netbox_contract/templates/netbox_contract/invoice.html
> Allow plugin to contract and invoice view

- src/netbox_contract/template_content.py
modified:   src/netbox_contract/template_content.py
> add contract to vm

- src/netbox_contract/template_content.py
modified:   src/netbox_contract/template_content.py
> Add contract assignement capability to sites

- README.md
- src/netbox_contract/api/serializers.py
- src/netbox_contract/api/views.py
- src/netbox_contract/tables.py
- src/netbox_contract/templates/netbox_contract/contract.html
- src/netbox_contract/views.py
modified:   src/netbox_contract/api/serializers.py
modified:   src/netbox_contract/api/views.py
modified:   src/netbox_contract/tables.py
modified:   src/netbox_contract/templates/netbox_contract/contract.html
modified:   src/netbox_contract/views.py
> Add read only caluclated yrc to contract

- README.md
- src/netbox_contract/__init__.py
- src/netbox_contract/api/serializers.py
- src/netbox_contract/navigation.py
- src/netbox_contract/template_content.py
- src/netbox_contract/templates/contract_assignments_bottom_old.html
- src/netbox_contract/templates/contract_list_bottom.html
- src/netbox_contract/templates/netbox_contract/contract.html
- src/netbox_contract/templates/netbox_contract/contract_assignment.html
- src/netbox_contract/templates/netbox_contract/invoice.html
- src/netbox_contract/templates/netbox_contract/serviceprovider.html
- src/netbox_contract/views.py
modified:   src/netbox_contract/__init__.py
modified:   src/netbox_contract/api/serializers.py
modified:   src/netbox_contract/navigation.py
modified:   src/netbox_contract/template_content.py
modified:   src/netbox_contract/templates/contract_assignments_bottom.html
new file:   src/netbox_contract/templates/contract_assignments_bottom_old.html
modified:   src/netbox_contract/templates/contract_list_bottom.html
modified:   src/netbox_contract/templates/netbox_contract/contract.html
modified:   src/netbox_contract/templates/netbox_contract/contract_assignment.html
modified:   src/netbox_contract/templates/netbox_contract/invoice.html
modified:   src/netbox_contract/templates/netbox_contract/serviceprovider.html
modified: …
> Prepare the migration to Netbox 4.0

- CHANGELOG.md
- src/netbox_contract/forms.py
Add more fields to the incoice and contract bulk edit forms
modified:   CHANGELOG.md
> Add more fields to the invoice and contract bef

- scripts/netbox-contract.py
Hi, 
Small Fix for Check_contract_end when the end_date is not defined
> fix check_contract_end with empty end date

- README.md
- src/netbox_contract/models.py
Fix typos for `Cancled` -> `Canceled`
> fix 2 typo for Canceled

- src/netbox_contract/tables.py
Hi,
Normally it's the last one missing
> feat(ui): add missing status bg color

- src/netbox_contract/models.py
Add last missing background color for contract and content object status when used with fk
> feat(ui): add missing bg color for content object fk status

- src/netbox_contract/tables.py
add and fix linkify object for accounting dimension
> fix(ui)AccountingDimension linkify objects

- src/netbox_contract/tables.py
Add tags `TagColumn` on every `ListTable` so you can have them in the tables and filter by tag
> feat(ui): add tags in tables

- .pre-commit-config.yaml
Syntax error on ruff hook.  
Remove Django specific checks.
> Correct liting and formating pre-commit hook

- README.md
To help with #234, fix some typos in the README.md file
> fix(typo) in README

- README.md
To support #234 adding the `('default', 'Default entity', 'green'),` on the README.md `FIELD_CHOICES`
> add default choice on internal partie as this is mandatory on the test

- netbox_contract/filtersets.py
- netbox_contract/forms.py
Hi,
Addition of missing filters to be able to filter contract by contract_type
> fix contract type filtering on contract

- netbox_contract/filtersets.py
- netbox_contract/forms.py
Hi,
Quick PR to add contact filtering on ServiceProvider where it's already possible to assign contact but not to filter with them.
Cheers,
Antoine
> add contact filtering on ServiceProvider

- CHANGELOG.md
- netbox_contract/filtersets.py
- netbox_contract/forms.py
- netbox_contract/models.py
- netbox_contract/tables.py
- netbox_contract/views.py
Hi @mlebreuil 
#249 
Add contacts to contract model + table + filtering
> #249 add contacts to contract
